"""
Install the Google AI Python SDK

$ pip install google-generativeai
"""
import subprocess
import sys
result = subprocess.run(["pip", "show", "google"], capture_output=True, text=True)
if len(result.stderr) !=0:
                  subprocess.check_call([sys.executable, "-m", "pip", "install", "google"])
        
import os
import google.generativeai as genai
import dotenv


genai.configure(api_key='AIzaSyB_sKDuWmC-qGmpPLf-WXp9nnvNIfCh_M8')


# Create the model
generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "max_output_tokens": 2048,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.0-pro",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
)
currentDir= os.path.dirname(os.path.abspath(__file__))
#print(currentDir,end="\n")
inputsDIR="resources\\gemini\\input file.txt"
outputsDIR="resources\\gemini\\output file.txt"
chat_session = model.start_chat(
  history=[
  ]
)
with open(inputsDIR,'r') as inputs, open(outputsDIR,'r') as outputs:
  inputfile= inputs.read()
  outputfile=outputs.read()
response = chat_session.send_message(f"From now on act as a compiler, I am going to provide you with a code written in Language X alongside its translated code written in language Y generated by my trans-compiler tool. Your task is to carefully examine the translated code in language Y and fill in the code sections that are missing in Y but present in X. These missing sections will be indicated by #TCAIOSAC and if there is something wrong in the syntax of the code fix it. if you didn't find it and the code is fine, write the full code in the language y. write it without backticks and any other statements.do not forget to remove #TCAIOSAC. the first code is ```{inputfile}``` and the second code is ```{outputfile}```")
with open("resources\\gemini\\final output.txt",'w') as final:
  final.write(response.text)
  final.close()
print(response.text)
